name=7Semi MCP4728
version=1.0.0
author=7Semi
maintainer=7Semi <info@7semi.com>
sentence=Arduino library for the MCP4728 4-channel 12-bit DAC over I2C.
paragraph=Supports fast write, multi write, sequential write with optional EEPROM, general call update, and full DAC/EERPOM readback functionality.
category=Signal Input/Output
url=https://github.com/7semi-solutions/7Semi-MCP4728
architectures=*
includes=7Semi_MCP4728.h
